name: Publish to GitHub Pages

on:
  workflow_run:
    workflows: ["Setup Next.js Project"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: nextjs-build
        path: ./out

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: ./out  # The directory with the static files from `next export`
